Remove last raw_data_dict reference
calpoly-csai/api pull request #106
Opened 2020-03-03 01:48 UTC by Jason-Ku

## What's New?
raw_data_dict -> data_dict

## Type of change (pick-one)
- [x] Bug fix (_non-breaking change which fixes an issue_)
- [ ] New feature (_non-breaking change which adds functionality_)
- [ ] Breaking change (_fix or feature that would cause existing functionality to not work as expected_)
- [ ] This change requires a documentation update

## How Has This Been Tested?
sanity tested

## Checklist (check-all-before-merge)
_formatting help: `- [x]` means "checked' and `- [ ]` means "unchecked"_

- [ ] I documented my code according to the [Google Python Style Guide][1]

- [ ] I ran `./build_docs.sh` and the docs look fine

- [ ] I ran `./type_check.sh` and got no errors

- [ ] I ran `./format.sh` because it automatically cleans my code for me 😄 

- [ ] I ran `./lint.sh` to check for what "format" missed

- [ ] I added my tests to the `/tests` directory

- [ ] I ran `./run_tests.sh` and all the tests pass

[1]: https://google.github.io/styleguide/pyguide.html

2020-03-03 06:01 UTC, Waidhoferj approved these changes
Thanks for catching that

2020-03-03 19:26 UTC, cameron-toy reviewed
necessary bug fix

2020-03-03 20:26 UTC, mfekadu requested changes
I agree that this fix is necessary! Good catch @Jason-Ku ! 

Can we include, at least 1 new test case into the [`/tests/`](https://github.com/calpoly-csai/api/tree/dev/tests)  folder

Including a new test will help to prevent this bug from occurring ever again. 

Also, it’s good software engineering practice. 

Run `pytest` and make sure that new test passes. Feel free to disregard other failing tests. 

It will be equivalent to your 
> sanity test

Except this time, documented and committed. 

The team has surely written many tests within `__main__` by now. Let’s just make sure to save those tests.

2020-03-04 17:29 UTC, Jason-Ku commented
> I agree that this fix is necessary! Good catch @Jason-Ku !
> 
> Can we include, at least 1 new test case into the [`/tests/`](https://github.com/calpoly-csai/api/tree/dev/tests) folder
> 
> Including a new test will help to prevent this bug from occurring ever again.
> 
> Also, it’s good software engineering practice.
> 
> Run `pytest` and make sure that new test passes. Feel free to disregard other failing tests.
> 
> It will be equivalent to your
> 
> > sanity test
> 
> Except this time, documented and committed.
> 
> The team has surely written many tests within `__main__` by now. Let’s just make sure to save those tests.

For sure!

2020-03-09 00:40 UTC, closed without merging