AudioMetadata lives again!!!!
calpoly-csai/api pull request #148
Opened 2020-05-15 04:28 UTC by Waidhoferj

## What's New?
**AudioMetadata is dead, long live AudioMetadata!** The prodigal son returns from the depths of rebase hell... sort of. The branch was so many commits behind that it was easier to just reimplement the PR. So this is more like AudioMetadata's clone, here to avenge the death of AudioMetadata.

**Basically the changes are the same:**
- Added ``emphasis`` and ``script`` fields to AudioSampleMetadata
- Swapped filename with audio_file_id, which will be far more useful for retrieving it from G Drive
- Added a couple of validations and formats to cover the new fields
- NEW ONE: if you don't send an audio file, the api be like "WTF dude"

## How Has This Been Tested?
Postman. I sent partial data packages to ensure that it would reject, and data packages with the wrong values and types. The validator is pretty strict. It does its job well.

2020-05-15 19:05 UTC, snekiam approved these changes
Looks good to me! I'm not sure what I did to cause git to be so angry which caused you to need to revive AudioMetadata, sorry about that.

2020-05-15 19:05 UTC, snekiam commented on flask_api.py
> +         return f"Failed to save audio file because... {err}", BAD_REQUEST
Love me some real error handling!

2020-05-15 19:05 UTC, snekiam commented on flask_api.py
> +     """
Docstrings? Sign me up!

2020-05-15 19:52 UTC, snekiam commented
Actually it looks like run_tests was passing on the last merge and they're failing now - I think one of the tests needs to be updated @Waidhoferj

2020-05-15 20:39 UTC, Jason-Ku requested changes
Some flask app tests are failing, and I'm not sure why. I think they might be too strict, but it's worth some investigation. Also, `TEST_AUDIO_SAMPLE_META_DATA_DATA_DICT` in test_database_wrapper.py needs a quick update with your new column names.

I'll take another look at the tests, but the PR looks pretty good to me.

2020-05-16 17:34 UTC, Waidhoferj commented
@Jason-Ku I was able to refactor two of the tests to reflect the use cases for the updated schema. However ``test_new_data_wakeword_db_error`` might need to be rewritten or removed. I don't think we use ``save_audio_sample_meta_data`` at all anymore, and the validation should be handled by the ``WakeWordValidator`` instead of the database wrapper. Lmk what you think.

2020-05-17 19:02 UTC, Jason-Ku commented
> @Jason-Ku I was able to refactor two of the tests to reflect the use cases for the updated schema. However `test_new_data_wakeword_db_error` might need to be rewritten or removed. I don't think we use `save_audio_sample_meta_data` at all anymore, and the validation should be handled by the `WakeWordValidator` instead of the database wrapper. Lmk what you think.

That sounds good to me, makes more sense to test the validator itself, so I think removing it is the right call here.

2020-05-17 21:23 UTC, Jason-Ku approved these changes
Looks good to me! thanks for updating the tests

2020-05-17 21:25 UTC, snekiam approved these changes

2020-05-17 21:52 UTC, merged